Repository SAP-docs/btp-cloud-platform, pull requests merged in 2022-01, with the labels that each got.

#13 correct link to abapGit repository
  docs/30-development/install-and-set-up-abapgit-2002380.md
Labels: type/linking, ua-review

#29 Update setting-up-trust-between-identity-authentication-and-sap-btp-9…
  docs/40-extensions/setting-up-trust-between-identity-authentication-and-sap-btp-9dba751.md
Labels: type/spelling-grammar, ua-review

#27 Update register-the-assertion-consumer-service-of-the-subaccount-in-s…
  docs/40-extensions/register-the-assertion-consumer-service-of-the-subaccount-in-sap-btp-in-sap-successfactor-8072e48.md
Labels: follow-up-with/dev, type/content-gaps, ua-review
