Repository SAP-docs/btp-cloud-platform, pull requests merged in 2023-07, with the labels that each got.

#161 Update development-c2fec62.md
  docs/30-development/development-c2fec62.md
Labels: type/content-gaps, environment/kyma

#163 Update development-c2fec62.md
  docs/30-development/development-c2fec62.md
Labels: ua-review, environment/kyma

#162 Update create-a-communication-arrangement-b7a87fd.md
  docs/50-administration-and-ops/create-a-communication-arrangement-b7a87fd.md
Labels: type/clarity, ua-review

#164 Update kyma-environment-468c2f3.md
  docs/10-concepts/kyma-environment-468c2f3.md
Labels: needs-more-info, size/s, type/outdated, ua-review, environment/kyma

#165 fix: typo
  docs/30-development/skip-and-top-options-e327980.md
Labels: type/spelling-grammar

#166 Update development-c2fec62.md
  docs/30-development/development-c2fec62.md
Labels: size/s, type/content-structure, ua-review, environment/kyma
